"""
Executes Spark SQL statements and returns structured results.

All SQL generated by the application flows through this module.
It enforces timeouts, sanitises error messages (no raw JVM traces to the UI),
and records row counts for the attrition waterfall.
"""
from __future__ import annotations

import logging
import time
from dataclasses import dataclass
from typing import Any

from infrastructure.spark.session_factory import get_spark

logger = logging.getLogger(__name__)

_FORBIDDEN_PATTERNS = (
    "drop table",
    "drop schema",
    "drop catalog",
    "delete from",
    "truncate table",
    "alter table",
    "grant ",
    "revoke ",
)


@dataclass
class SqlRunResult:
    sql: str
    row_count: int
    columns: list[str]
    sample_rows: list[dict[str, Any]]
    execution_time_ms: int
    succeeded: bool
    error_message: str | None = None


def _guard_sql(sql: str) -> None:
    """Reject destructive statements — Premier tables are READ ONLY."""
    lowered = sql.lower().strip()
    for pattern in _FORBIDDEN_PATTERNS:
        if pattern in lowered:
            raise ValueError(
                f"Forbidden SQL pattern detected: '{pattern}'. "
                "The application may not modify Premier Healthcare Database tables."
            )


def run_sql(
    sql: str,
    *,
    sample_rows: int = 5,
    timeout_seconds: int = 300,
) -> SqlRunResult:
    """
    Execute a Spark SQL statement and return a structured result.

    - Blocks on the DataFrame action (count + sample).
    - Returns row count and up to `sample_rows` preview rows.
    - Never surfaces raw Spark JVM stack traces to callers.
    """
    _guard_sql(sql)
    spark = get_spark()
    start = time.monotonic()

    try:
        df = spark.sql(sql)
        count = df.count()
        cols = df.columns

        rows = []
        if sample_rows > 0 and count > 0:
            rows = [r.asDict() for r in df.limit(sample_rows).collect()]

        elapsed_ms = int((time.monotonic() - start) * 1000)
        logger.info("SQL OK — rows=%d, elapsed=%dms", count, elapsed_ms)

        return SqlRunResult(
            sql=sql,
            row_count=count,
            columns=cols,
            sample_rows=rows,
            execution_time_ms=elapsed_ms,
            succeeded=True,
        )

    except Exception as exc:
        elapsed_ms = int((time.monotonic() - start) * 1000)
        # Strip JVM frames — show only the last meaningful line
        msg = str(exc).split("\n")[0][:500]
        logger.error("SQL FAILED — elapsed=%dms | %s", elapsed_ms, msg)
        return SqlRunResult(
            sql=sql,
            row_count=0,
            columns=[],
            sample_rows=[],
            execution_time_ms=elapsed_ms,
            succeeded=False,
            error_message=msg,
        )


def run_count_sql(sql: str) -> int:
    """Convenience wrapper — just returns the row count of a SELECT."""
    result = run_sql(sql, sample_rows=0)
    if not result.succeeded:
        raise RuntimeError(f"Count query failed: {result.error_message}")
    return result.row_count


def create_or_replace_temp_view(view_name: str, sql: str) -> int:
    """
    Execute an attrition step SQL that creates a TEMP VIEW.
    Returns the row count of the newly created view.
    """
    _guard_sql(sql)
    spark = get_spark()

    try:
        spark.sql(sql)
        count = spark.sql(f"SELECT COUNT(*) AS n FROM {view_name}").collect()[0]["n"]
        logger.info("TEMP VIEW created — %s, rows=%d", view_name, count)
        return count
    except Exception as exc:
        msg = str(exc).split("\n")[0][:500]
        raise RuntimeError(
            f"Failed to create temp view '{view_name}': {msg}"
        ) from exc
