"""
Hardcoded Premier business rules for SQL generation.

These rules encode the critical invariants from CLAUDE.md and PHD documentation.
They are seeded into Delta on every ingestion run and injected into SQL prompts
via MetadataContext.to_prompt_text().

Rules are NOT generated by an LLM — they are curated domain knowledge.
"""
from __future__ import annotations

from domain.ports.metadata_port import BusinessRule


def get_premier_business_rules() -> list[BusinessRule]:
    return list(_RULES)


_RULES: list[BusinessRule] = [
    # ── Patient identification ────────────────────────────────────────────────
    BusinessRule(
        rule_id="rule_pat_key_join",
        rule_name="pat_key is the encounter join key",
        rule_category="join_key",
        description=(
            "All patient-level tables join via pat_key (encounter key). "
            "pat_key is NOT a unique patient identifier — one patient can have many pat_keys. "
            "Use medrec_key to track a patient across multiple encounters."
        ),
        sql_pattern=(
            "JOIN {table} ON patdemo.pat_key = {table}.pat_key"
        ),
        applicable_tables=[
            "patdemo", "paticd_diag", "paticd_proc", "patcpt",
            "patbill", "genlab", "vitals", "proc_supply", "pat_sdoh",
        ],
    ),
    BusinessRule(
        rule_id="rule_medrec_key_join",
        rule_name="medrec_key is the patient-level join key",
        rule_category="join_key",
        description=(
            "MORTALITY and TOKENS join on medrec_key (patient key), NOT pat_key. "
            "medrec_key identifies a unique patient across all encounters."
        ),
        sql_pattern=(
            "JOIN {table} ON patdemo.medrec_key = {table}.medrec_key"
        ),
        applicable_tables=["mortality", "tokens"],
    ),

    # ── ICD version handling ──────────────────────────────────────────────────
    BusinessRule(
        rule_id="rule_icd_version_required",
        rule_name="ICD joins MUST include icd_version",
        rule_category="icd_coding",
        description=(
            "ICD-9 and ICD-10 code ranges overlap — the same numeric string can mean "
            "different diagnoses in ICD-9 vs ICD-10. "
            "ALWAYS include icd_version in the join to icdcode and in WHERE filters. "
            "ICD-9 was used through Sept 30 2015; ICD-10 from Oct 1 2015 onwards."
        ),
        sql_pattern=(
            "JOIN icdcode ON paticd_diag.icd_code = icdcode.icd_code "
            "AND paticd_diag.icd_version = icdcode.icd_version"
        ),
        applicable_tables=["paticd_diag", "paticd_proc", "icdcode"],
    ),
    BusinessRule(
        rule_id="rule_icd_cutover_date",
        rule_name="ICD-9 to ICD-10 transition date",
        rule_category="icd_coding",
        description=(
            "ICD-9 codes were used for discharges on or before Sept 30 2015 (disc_mon <= '201509'). "
            "ICD-10 codes were used for discharges on or after Oct 1 2015 (disc_mon >= '201510'). "
            "When filtering by a specific ICD version, filter disc_mon accordingly."
        ),
        sql_pattern=(
            "-- ICD-9: disc_mon <= '201509'\n"
            "-- ICD-10: disc_mon >= '201510'"
        ),
        applicable_tables=["patdemo", "paticd_diag", "paticd_proc"],
    ),

    # ── Inpatient filter ──────────────────────────────────────────────────────
    BusinessRule(
        rule_id="rule_inpatient_filter",
        rule_name="Inpatient encounter filter",
        rule_category="encounter_type",
        description=(
            "To restrict to inpatient encounters, filter on i_o_ind = 'I' or pat_type = '08'. "
            "i_o_ind is present in patdemo and prov_enrollment. "
            "pat_type = '08' is the standard Premier inpatient code."
        ),
        sql_pattern=(
            "WHERE i_o_ind = 'I'  -- or: WHERE pat_type = '08'"
        ),
        applicable_tables=["patdemo", "prov_enrollment"],
    ),

    # ── Provider enrollment join ──────────────────────────────────────────────
    BusinessRule(
        rule_id="rule_prov_enrollment_join",
        rule_name="PROV_ENROLLMENT requires 3-column join",
        rule_category="join_key",
        description=(
            "Joining to prov_enrollment requires ALL THREE: prov_id, disc_mon, AND i_o_ind = 'I'. "
            "Omitting any of these three columns produces incorrect results (fan-out or wrong rows)."
        ),
        sql_pattern=(
            "JOIN prov_enrollment ON patdemo.prov_id = prov_enrollment.prov_id "
            "AND patdemo.disc_mon = prov_enrollment.disc_mon "
            "AND prov_enrollment.i_o_ind = 'I'"
        ),
        applicable_tables=["patdemo", "prov_enrollment"],
    ),

    # ── Add-on licensing ──────────────────────────────────────────────────────
    BusinessRule(
        rule_id="rule_addon_license",
        rule_name="Add-on tables require additional Premier licensing",
        rule_category="licensing",
        description=(
            "The following tables require an additional Premier add-on license and may not be "
            "available in all Premier data extracts: "
            "GENLAB, VITALS, LAB_RES, LAB_SENS, PROC_SUPPLY, MORTALITY, TOKENS, "
            "MOTHER_INFANT_LINK, PAT_SDOH. "
            "Always add '-- ADD-ON LICENSE REQUIRED' comment when using these tables."
        ),
        sql_pattern="-- ADD-ON LICENSE REQUIRED",
        applicable_tables=[
            "genlab", "vitals", "lab_res", "lab_sens", "proc_supply",
            "mortality", "tokens", "mother_infant_link", "pat_sdoh",
        ],
    ),

    # ── Date format ───────────────────────────────────────────────────────────
    BusinessRule(
        rule_id="rule_disc_mon_format",
        rule_name="disc_mon is YYYYMM string format",
        rule_category="date_handling",
        description=(
            "disc_mon (discharge month) is stored as a 6-character string in YYYYMM format "
            "(e.g. '202301' for January 2023). "
            "Use string comparison for date range filters: disc_mon BETWEEN '202001' AND '202312'. "
            "Do NOT cast to date unless explicitly needed."
        ),
        sql_pattern=(
            "WHERE disc_mon BETWEEN '202001' AND '202312'"
        ),
        applicable_tables=["patdemo", "prov_enrollment"],
    ),

    # ── ROW_NUMBER deduplication ──────────────────────────────────────────────
    BusinessRule(
        rule_id="rule_row_number_not_rank",
        rule_name="Use ROW_NUMBER() not RANK() for deduplication",
        rule_category="sql_pattern",
        description=(
            "Always use ROW_NUMBER() OVER (PARTITION BY ... ORDER BY ...) for deduplication. "
            "Never use RANK() unless there is a specific documented reason — "
            "RANK() can produce ties that break exactly-one-row guarantees."
        ),
        sql_pattern=(
            "ROW_NUMBER() OVER (PARTITION BY pat_key ORDER BY disc_mon DESC) AS rn"
        ),
        applicable_tables=[],
    ),

    # ── Temp view naming ──────────────────────────────────────────────────────
    BusinessRule(
        rule_id="rule_temp_view_naming",
        rule_name="Temp views must follow ads_attrition naming convention",
        rule_category="sql_pattern",
        description=(
            "Every attrition step SQL must produce a temp view named: "
            "ads_attrition_{session_id}_{step_num}_{slug}. "
            "This convention prevents name collisions across concurrent sessions."
        ),
        sql_pattern=(
            "CREATE OR REPLACE TEMP VIEW ads_attrition_{session_id}_{step_num}_{slug} AS"
        ),
        applicable_tables=[],
    ),

    # ── Index event deduplication ─────────────────────────────────────────────
    BusinessRule(
        rule_id="rule_index_event_dedup",
        rule_name="Index event: one encounter per patient",
        rule_category="cohort_design",
        description=(
            "When identifying an index event, select ONE encounter per patient "
            "using ROW_NUMBER() partitioned by medrec_key. "
            "Typically take the FIRST qualifying encounter (ORDER BY disc_mon ASC) "
            "unless the protocol specifies otherwise."
        ),
        sql_pattern=(
            "ROW_NUMBER() OVER (PARTITION BY medrec_key ORDER BY disc_mon ASC) AS rn\n"
            "-- WHERE rn = 1 to keep only the first index encounter"
        ),
        applicable_tables=["patdemo", "paticd_diag"],
    ),
]
