"""
Hardcoded Premier table join relationships.

These relationships are stable domain knowledge from the PHD V2.2 documentation
and CLAUDE.md join rules.  They are NOT generated by an LLM — they encode the
critical facts that make SQL generation correct:

  - All patient-level tables join via pat_key (encounter key)
  - MORTALITY and TOKENS join via medrec_key (patient key)
  - ICD joins ALWAYS include icd_version — ICD-9 and ICD-10 codes overlap
  - PROV_ENROLLMENT joins: prov_id AND disc_mon AND i_o_ind = 'I'

This module is the authoritative source for relationship metadata.
MetadataIngestor seeds these into Delta on every ingestion run.
"""
from __future__ import annotations

from domain.ports.metadata_port import RelationshipMetadata


def get_premier_relationships() -> list[RelationshipMetadata]:
    """Return the full set of hardcoded Premier join relationships."""
    return [r for r in _RELATIONSHIPS]


# ── Primary encounter join (pat_key) ──────────────────────────────────────────

_RELATIONSHIPS: list[RelationshipMetadata] = [
    RelationshipMetadata(
        relationship_id="rel_patdemo_paticd_diag",
        from_table="patdemo",
        from_column="pat_key",
        to_table="paticd_diag",
        to_column="pat_key",
        join_condition="patdemo.pat_key = paticd_diag.pat_key",
        join_type="LEFT",
        notes="Standard encounter join. Must also join icdcode on icd_code + icd_version.",
    ),
    RelationshipMetadata(
        relationship_id="rel_patdemo_paticd_proc",
        from_table="patdemo",
        from_column="pat_key",
        to_table="paticd_proc",
        to_column="pat_key",
        join_condition="patdemo.pat_key = paticd_proc.pat_key",
        join_type="LEFT",
        notes="Standard encounter join. Must also join icdcode on icd_code + icd_version.",
    ),
    RelationshipMetadata(
        relationship_id="rel_patdemo_patcpt",
        from_table="patdemo",
        from_column="pat_key",
        to_table="patcpt",
        to_column="pat_key",
        join_condition="patdemo.pat_key = patcpt.pat_key",
        join_type="LEFT",
        notes="Standard encounter join.",
    ),
    RelationshipMetadata(
        relationship_id="rel_patdemo_patbill",
        from_table="patdemo",
        from_column="pat_key",
        to_table="patbill",
        to_column="pat_key",
        join_condition="patdemo.pat_key = patbill.pat_key",
        join_type="LEFT",
        notes="Standard encounter join. Used for drug/supply billing.",
    ),
    RelationshipMetadata(
        relationship_id="rel_patdemo_genlab",
        from_table="patdemo",
        from_column="pat_key",
        to_table="genlab",
        to_column="pat_key",
        join_condition="patdemo.pat_key = genlab.pat_key",
        join_type="LEFT",
        notes="ADD-ON LICENSE REQUIRED. Standard encounter join.",
    ),
    RelationshipMetadata(
        relationship_id="rel_patdemo_vitals",
        from_table="patdemo",
        from_column="pat_key",
        to_table="vitals",
        to_column="pat_key",
        join_condition="patdemo.pat_key = vitals.pat_key",
        join_type="LEFT",
        notes="ADD-ON LICENSE REQUIRED. Standard encounter join.",
    ),
    RelationshipMetadata(
        relationship_id="rel_patdemo_proc_supply",
        from_table="patdemo",
        from_column="pat_key",
        to_table="proc_supply",
        to_column="pat_key",
        join_condition="patdemo.pat_key = proc_supply.pat_key",
        join_type="LEFT",
        notes="ADD-ON LICENSE REQUIRED. Device/supply data.",
    ),
    RelationshipMetadata(
        relationship_id="rel_patdemo_pat_sdoh",
        from_table="patdemo",
        from_column="pat_key",
        to_table="pat_sdoh",
        to_column="pat_key",
        join_condition="patdemo.pat_key = pat_sdoh.pat_key",
        join_type="LEFT",
        notes="ADD-ON LICENSE REQUIRED. Social determinants of health.",
    ),

    # ── medrec_key joins (patient-level, not encounter-level) ─────────────────
    RelationshipMetadata(
        relationship_id="rel_patdemo_mortality",
        from_table="patdemo",
        from_column="medrec_key",
        to_table="mortality",
        to_column="medrec_key",
        join_condition="patdemo.medrec_key = mortality.medrec_key",
        join_type="LEFT",
        notes="ADD-ON LICENSE REQUIRED. Join on medrec_key (patient), NOT pat_key.",
    ),
    RelationshipMetadata(
        relationship_id="rel_patdemo_tokens",
        from_table="patdemo",
        from_column="medrec_key",
        to_table="tokens",
        to_column="medrec_key",
        join_condition="patdemo.medrec_key = tokens.medrec_key",
        join_type="LEFT",
        notes="ADD-ON LICENSE REQUIRED. Join on medrec_key (patient), NOT pat_key.",
    ),

    # ── ICD code lookup (CRITICAL: always include icd_version) ────────────────
    RelationshipMetadata(
        relationship_id="rel_paticd_diag_icdcode",
        from_table="paticd_diag",
        from_column="icd_code",
        to_table="icdcode",
        to_column="icd_code",
        join_condition=(
            "paticd_diag.icd_code = icdcode.icd_code "
            "AND paticd_diag.icd_version = icdcode.icd_version"
        ),
        join_type="LEFT",
        notes=(
            "CRITICAL: Must join on BOTH icd_code AND icd_version. "
            "ICD-9 and ICD-10 share code values. "
            "ICD-9 used before Oct 1 2015; ICD-10 on or after."
        ),
    ),
    RelationshipMetadata(
        relationship_id="rel_paticd_proc_icdcode",
        from_table="paticd_proc",
        from_column="icd_code",
        to_table="icdcode",
        to_column="icd_code",
        join_condition=(
            "paticd_proc.icd_code = icdcode.icd_code "
            "AND paticd_proc.icd_version = icdcode.icd_version"
        ),
        join_type="LEFT",
        notes=(
            "CRITICAL: Must join on BOTH icd_code AND icd_version. "
            "ICD-9 and ICD-10 share code values."
        ),
    ),

    # ── CPT code lookup ────────────────────────────────────────────────────────
    RelationshipMetadata(
        relationship_id="rel_patcpt_cptcode",
        from_table="patcpt",
        from_column="cpt_code",
        to_table="cptcode",
        to_column="cpt_code",
        join_condition="patcpt.cpt_code = cptcode.cpt_code",
        join_type="LEFT",
        notes="CPT procedure code lookup.",
    ),

    # ── Payer lookup ───────────────────────────────────────────────────────────
    RelationshipMetadata(
        relationship_id="rel_patdemo_payor",
        from_table="patdemo",
        from_column="payer_id",
        to_table="payor",
        to_column="payer_id",
        join_condition="patdemo.payer_id = payor.payer_id",
        join_type="LEFT",
        notes="Payer category lookup.",
    ),

    # ── Provider enrollment (complex 3-column join) ────────────────────────────
    RelationshipMetadata(
        relationship_id="rel_patdemo_prov_enrollment",
        from_table="patdemo",
        from_column="prov_id",
        to_table="prov_enrollment",
        to_column="prov_id",
        join_condition=(
            "patdemo.prov_id = prov_enrollment.prov_id "
            "AND patdemo.disc_mon = prov_enrollment.disc_mon "
            "AND prov_enrollment.i_o_ind = 'I'"
        ),
        join_type="INNER",
        notes=(
            "CRITICAL 3-column join: prov_id + disc_mon + i_o_ind = 'I'. "
            "Used for continuous enrollment and hospital cohort filters."
        ),
    ),

    # ── Admit type / discharge status lookups ─────────────────────────────────
    RelationshipMetadata(
        relationship_id="rel_patdemo_admtype",
        from_table="patdemo",
        from_column="admit_type",
        to_table="admtype",
        to_column="admit_type",
        join_condition="patdemo.admit_type = admtype.admit_type",
        join_type="LEFT",
        notes="Admission type description lookup.",
    ),
    RelationshipMetadata(
        relationship_id="rel_patdemo_disstat",
        from_table="patdemo",
        from_column="disc_status",
        to_table="disstat",
        to_column="disc_status",
        join_condition="patdemo.disc_status = disstat.disc_status",
        join_type="LEFT",
        notes="Discharge status description lookup.",
    ),

    # ── DRG lookups ───────────────────────────────────────────────────────────
    RelationshipMetadata(
        relationship_id="rel_patdemo_msdrg",
        from_table="patdemo",
        from_column="ms_drg",
        to_table="msdrg",
        to_column="ms_drg",
        join_condition="patdemo.ms_drg = msdrg.ms_drg",
        join_type="LEFT",
        notes="MS-DRG description lookup.",
    ),

    # ── Charge master (drug/supply) ────────────────────────────────────────────
    RelationshipMetadata(
        relationship_id="rel_patbill_chgmstr",
        from_table="patbill",
        from_column="std_chg_code",
        to_table="chgmstr",
        to_column="std_chg_code",
        join_condition="patbill.std_chg_code = chgmstr.std_chg_code",
        join_type="LEFT",
        notes="Charge master description and classification for billing items.",
    ),

    # ── Mother-infant link ─────────────────────────────────────────────────────
    RelationshipMetadata(
        relationship_id="rel_patdemo_mother_infant",
        from_table="patdemo",
        from_column="pat_key",
        to_table="mother_infant_link",
        to_column="infant_pat_key",
        join_condition="patdemo.pat_key = mother_infant_link.infant_pat_key",
        join_type="LEFT",
        notes="ADD-ON LICENSE REQUIRED. Links infant encounters to mother encounters.",
    ),
]
